// <auto-generated />
namespace JavnaRasprava.WEB.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InitalProduction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitalProduction));
        
        string IMigrationMetadata.Id
        {
            get { return "201602092116314_InitalProduction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
