// <auto-generated />
namespace JavnaRasprava.WEB.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class emailbugs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emailbugs));
        
        string IMigrationMetadata.Id
        {
            get { return "201703282231433_emailbugs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
