// <auto-generated />
namespace JavnaRasprava.WEB.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class subdomain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subdomain));
        
        string IMigrationMetadata.Id
        {
            get { return "201801211051199_subdomain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
