//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavnaRasprava.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Routes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Routes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JavnaRasprava.WEB.App_GlobalResources.Routes", typeof(Routes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to def.Admin.Index.
        /// </summary>
        public static string Admin_Index {
            get {
                return ResourceManager.GetString("Admin_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.AllLaws.Index.
        /// </summary>
        public static string AllLaws_Index {
            get {
                return ResourceManager.GetString("AllLaws_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.AllSections.Details.
        /// </summary>
        public static string AllSections_Details {
            get {
                return ResourceManager.GetString("AllSections_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.AllSections.Index.
        /// </summary>
        public static string AllSections_Index {
            get {
                return ResourceManager.GetString("AllSections_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavnaRasprava.
        /// </summary>
        public static string JavnaRasprava {
            get {
                return ResourceManager.GetString("JavnaRasprava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to def.JavnaRasprava.Index.
        /// </summary>
        public static string JavnaRasprava_Index {
            get {
                return ResourceManager.GetString("JavnaRasprava_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.JavnaRasprava.LawDetails.
        /// </summary>
        public static string JavnaRasprava_LawDetails {
            get {
                return ResourceManager.GetString("JavnaRasprava_LawDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.News.Details.
        /// </summary>
        public static string News_Details {
            get {
                return ResourceManager.GetString("News_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.News.Index.
        /// </summary>
        public static string News_Index {
            get {
                return ResourceManager.GetString("News_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Petition.
        /// </summary>
        public static string Petition {
            get {
                return ResourceManager.GetString("Petition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.Quiz.Index.
        /// </summary>
        public static string Quiz_Index {
            get {
                return ResourceManager.GetString("Quiz_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Representatives.
        /// </summary>
        public static string Representatives {
            get {
                return ResourceManager.GetString("Representatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.Representatives.Index.
        /// </summary>
        public static string Representatives_Index {
            get {
                return ResourceManager.GetString("Representatives_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.Representatives.Representative.
        /// </summary>
        public static string Representatives_Representative {
            get {
                return ResourceManager.GetString("Representatives_Representative", resourceCulture);
            }
        }
    }
}
