//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavnaRasprava.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticPageData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticPageData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JavnaRasprava.WEB.App_GlobalResources.StaticPageData", typeof(StaticPageData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nama.
        /// </summary>
        public static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javna rasprava.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javna rasprava Tuzlanski kanton.
        /// </summary>
        public static string Credits_Tuzla {
            get {
                return ResourceManager.GetString("Credits_Tuzla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobro došli na stranicu javnarasprava.ba  Ukoliko želite komunicirati i postavljati pitanja poslanicima/cama u Skupštini Tuzlanskog kantona pozivamo vas da posjetite našu novu stranicu — &lt;strong&gt;javnaraspravatk.ba&lt;/strong&gt;.
        /// </summary>
        public static string HomePage_Footer {
            get {
                return ResourceManager.GetString("HomePage_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobro došli na stranicu za komunikaciju sa poslanicima Skupštine Tuzlanskog kantona. Ukoliko želite komunicirati i postavljati pitanja parlamentarcima i parlamentarkama u parlamentima na državnom i entitetskim nivoima pozivamo vas da posjetite centralnu stranicu — &lt;strong&gt;javnarasprava.ba&lt;/strong&gt;.
        /// </summary>
        public static string HomePage_Footer_Tuzla {
            get {
                return ResourceManager.GetString("HomePage_Footer_Tuzla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite neki od parlamenata na državnom ili entitetskim nivoima i učestvujte u javnoj raspravi o zakonima koji su trenutno u proceduri..
        /// </summary>
        public static string HomePage_JavnaRasprava_Description {
            get {
                return ResourceManager.GetString("HomePage_JavnaRasprava_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učestvujte u javnoj raspravi o zakonima koji su trenutno u proceduri u Skupštini Tuzlanskog kantona..
        /// </summary>
        public static string HomePage_JavnaRasprava_Description_Tuzla {
            get {
                return ResourceManager.GetString("HomePage_JavnaRasprava_Description_Tuzla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javna rasprava.
        /// </summary>
        public static string HomePage_JavnaRasprava_Title {
            get {
                return ResourceManager.GetString("HomePage_JavnaRasprava_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli.
        /// </summary>
        public static string HomePage_PageTitle {
            get {
                return ResourceManager.GetString("HomePage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokrenite peticiju i zahtijevajte reakciju odgovornih predstavika vlasti! Promovirajte vaše inicijative i tražite podršku i solidarnost ostalih građana/ki..
        /// </summary>
        public static string HomePage_Petition_Description {
            get {
                return ResourceManager.GetString("HomePage_Petition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokrenite peticiju.
        /// </summary>
        public static string HomePage_Petition_Title {
            get {
                return ResourceManager.GetString("HomePage_Petition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavite pitanja i komunicirajte sa parlamentarcima. 
        ///                Saznajte koliko su odgovorni prema građanima/kama koji su ih birali na te pozicije..
        /// </summary>
        public static string HomePage_Representatives_Description {
            get {
                return ResourceManager.GetString("HomePage_Representatives_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavite pitanja i komunicirajte sa poslanicima/cama. Saznajte koliko su odgovorni prema građanima/kama koji su ih birali na te pozicije..
        /// </summary>
        public static string HomePage_Representatives_Description_Tuzla {
            get {
                return ResourceManager.GetString("HomePage_Representatives_Description_Tuzla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitaj parlamentarca.
        /// </summary>
        public static string HomePage_Representatives_Title {
            get {
                return ResourceManager.GetString("HomePage_Representatives_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitaj poslanike.
        /// </summary>
        public static string HomePage_Representatives_Title_Tuzla {
            get {
                return ResourceManager.GetString("HomePage_Representatives_Title_Tuzla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uputstvo za korištenje.
        /// </summary>
        public static string Manual_PageTitle {
            get {
                return ResourceManager.GetString("Manual_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nama.
        /// </summary>
        public static string Navigation_About {
            get {
                return ResourceManager.GetString("Navigation_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uputstvo za korištenje.
        /// </summary>
        public static string Navigation_Manual {
            get {
                return ResourceManager.GetString("Navigation_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peticije.
        /// </summary>
        public static string Navigation_Petitions {
            get {
                return ResourceManager.GetString("Navigation_Petitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitaj parlamentarce.
        /// </summary>
        public static string Navigation_Representatives {
            get {
                return ResourceManager.GetString("Navigation_Representatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavnaRasprava.ba.
        /// </summary>
        public static string PageTitleSufix {
            get {
                return ResourceManager.GetString("PageTitleSufix", resourceCulture);
            }
        }
    }
}
